import type { Id } from '../../convex/_generated/dataModel'

// ============================================================
// TriageOS MVP - Shared TypeScript Types
// ============================================================

// ── Triage Core ─────────────────────────────────────────────

export type RiskLevel = 'High' | 'Medium' | 'Low'

export interface TriageNote {
  chiefComplaint: string
  onset: string
  symptoms: string[]
  riskLevel: RiskLevel
  esiLevel: 1 | 2 | 3 | 4 | 5
  suggestedAction: string
  clinicalSummary: string
  /** AI confidence score 0–100, only present when generated by real AI */
  confidenceScore?: number
}

export interface TriageSession {
  id: string
  patientId: string
  convexPatientId?: Id<'patients'>
  patientName?: string
  patientBpjsId?: string
  transcript: string
  images: string[]      // base64 data URLs
  uploadedPhotoStorageIds?: Id<'_storage'>[]
  triageNote: TriageNote | null
  timestamp: string     // ISO string (localStorage serialization)
  esiLevel: number | null
  vitals?: VitalSignsInput
  status?: TriageSessionStatus
}

// ── Session Form State ───────────────────────────────────────

export interface TriageFormState {
  patientId: string
  convexPatientId: Id<'patients'> | null
  selectedPatient: Patient | null
  transcript: string
  images: string[]
  uploadedPhotoStorageIds: Id<'_storage'>[]
  triageNote: TriageNote | null
  vitals: VitalSignsInput
  isGenerating: boolean
  isSaving: boolean
  error: string | null
  viewingSessionId: string | null  // non-null when viewing a past session
}

// ── Speech Recognition ───────────────────────────────────────

export type SpeechStatus = 'idle' | 'listening' | 'unavailable'

export interface SpeechState {
  status: SpeechStatus
  interimTranscript: string
  finalTranscript: string
  isAvailable: boolean
  error: string | null
}

// ── Session List Item (sidebar) ─────────────────────────────

export type SessionListItem = Pick<TriageSession, 'id' | 'patientId' | 'patientName' | 'timestamp' | 'esiLevel' | 'transcript'>

export type TriageSavePayload = {
  patientId: string
  convexPatientId?: Id<'patients'> | null
  selectedPatient?: Patient | null
  patientName?: string
  transcript: string
  images: string[]
  uploadedPhotoStorageIds?: Id<'_storage'>[]
  triageNote: TriageNote | null
  esiLevel: number | null
  vitals: VitalSignsInput
  status?: TriageSessionStatus
}

export type StaffRole = 'doctor' | 'nurse' | 'admin' | 'staff'
export type TriageSessionStatus = 'draft' | 'generated' | 'completed'

// ── ESI Color / Label Constants ────────────────────────────

export const ESI_COLORS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: 'bg-red-500',
  2: 'bg-orange-500',
  3: 'bg-yellow-400',
  4: 'bg-green-500',
  5: 'bg-blue-500',
}

export const ESI_TEXT_COLORS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: 'text-red-700',
  2: 'text-orange-700',
  3: 'text-yellow-700',
  4: 'text-green-700',
  5: 'text-blue-700',
}

export const ESI_BG_LIGHT: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: 'bg-red-50',
  2: 'bg-orange-50',
  3: 'bg-yellow-50',
  4: 'bg-green-50',
  5: 'bg-blue-50',
}

export const ESI_BORDER_COLORS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: 'border-red-500',
  2: 'border-orange-500',
  3: 'border-yellow-400',
  4: 'border-green-500',
  5: 'border-blue-500',
}

export const ESI_LABELS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: 'Resuscitation',
  2: 'Emergent',
  3: 'Urgent',
  4: 'Less Urgent',
  5: 'Non-Urgent',
}

export const ESI_DESCRIPTIONS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: 'Ancaman jiwa langsung, harus ditangani segera',
  2: 'Risiko tinggi, waktu kritis <10 menit',
  3: 'Stable tapi butuh sumber daya ganda, <30 menit',
  4: 'Kurang urgent, butuh 1 sumber daya, <60 menit',
  5: 'Non-urgent, bisa menunggu',
}

// ── Toast ───────────────────────────────────────────────────

export type ToastType = 'success' | 'error' | 'info'

export interface ToastMessage {
  id: string
  type: ToastType
  message: string
}

// ── Vital Signs ─────────────────────────────────────────────

export interface VitalSignsInput {
  systolicBP?: number   // mmHg
  diastolicBP?: number  // mmHg
  heartRate?: number   // bpm
  spO2?: number        // % (85–100)
  temperature?: number // °C
  respiratoryRate?: number // /min
  gcs?: number         // 3–15
  painScore?: number   // 0–10
}

export interface ConvexVitalSignsInput {
  systolicBloodPressure?: number
  diastolicBloodPressure?: number
  heartRate?: number
  spo2?: number
  temperature?: number
  respiratoryRate?: number
  gcs?: number
  painScore?: number
}

export interface Patient {
  _id: Id<'patients'>
  bpjsId: string
  bpjsClass?: string
  nik?: string
  name: string
  medicalRecordNumber?: string
  gender?: string
  dateOfBirth?: string
  age?: number
  phoneNumber?: string
  address?: string
  createdAt?: number
  updatedAt?: number
}

export type PatientRecord = Patient

export interface StaffUser {
  _id: Id<'users'>
  googleId?: string
  name?: string
  email?: string
  avatarUrl?: string
  image?: string
  role?: StaffRole
  createdAt?: number
  updatedAt?: number
}

export type DoctorUser = StaffUser
export type AuthenticatedUser = StaffUser
export type UserProfile = StaffUser
export type VitalSigns = VitalSignsInput

// ── Mock Patient ─────────────────────────────────────────────

export interface MockPatient {
  patientId: string
  name: string
  dob: string
  bpjsClass: 'Kelas 1' | 'Kelas 2' | 'Kelas 3'
  address?: string
}
